services:
  eurostyle-clickhouse:
    container_name: ${CLICKHOUSE_CONTAINER_NAME:-eurostyle_clickhouse_retail}
    image: clickhouse/clickhouse-server:23.12
    restart: unless-stopped
    
    ports:
      - "${CLICKHOUSE_HTTP_PORT:-8124}:8123"  # HTTP interface - EuroStyle Retail Demo
      - "${CLICKHOUSE_NATIVE_PORT:-9002}:9000"  # Native interface - EuroStyle Retail Demo
    
    volumes:
      # Database initialization
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
      - ../DMShared/clickhouse/data:/var/lib/clickhouse:rw
      - ../DMShared/clickhouse/logs:/var/log/clickhouse-server:rw
      - ./config:/etc/clickhouse-server/config.d:ro
      - ./config/users.xml:/etc/clickhouse-server/users.d/users.xml:ro
      
    environment:
      CLICKHOUSE_DB: ${DEFAULT_DATABASE:-eurostyle_operational}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-eurostyle_user}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-eurostyle_demo_2024}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client --host=localhost --port=9000 --query='SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    networks:
      - eurostyle-retail-network
    
    # Resource limits for demo environment
    deploy:
      resources:
        limits:
          memory: ${CLICKHOUSE_MEMORY_LIMIT:-6G}
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'
  python:
    container_name: python_container
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    
    volumes:
      - ./ /app:rw
    
    working_dir: /app
    
    environment:
      CLICKHOUSE_HOST: ${CLICKHOUSE_HOST:-eurostyle-clickhouse}
      CLICKHOUSE_PORT: ${CLICKHOUSE_NATIVE_PORT:-9000}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-eurostyle_user}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-eurostyle_demo_2024}
      CLICKHOUSE_DATABASE: ${DEFAULT_DATABASE:-eurostyle_operational}
    
    networks:
      - eurostyle-retail-network
    
    depends_on:
      eurostyle-clickhouse:
        condition: service_healthy

networks:
  eurostyle-retail-network:
    driver: bridge
    name: ${DOCKER_NETWORK:-eurostyle_retail_network}

